// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAFVHhhri-fed0OKg_tr3jH3A8GAjLcKg',
    appId: '1:310222645693:web:662cab8ea8b568a0b94ad4',
    messagingSenderId: '310222645693',
    projectId: 'e-commerce-fa443',
    authDomain: 'e-commerce-fa443.firebaseapp.com',
    databaseURL: 'https://e-commerce-fa443-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'e-commerce-fa443.appspot.com',
    measurementId: 'G-3EP29PPX0W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbz6ZwRzYNkKcnVWFzhZUe1LY8Xh9pgMU',
    appId: '1:310222645693:android:07e62492e1abd111b94ad4',
    messagingSenderId: '310222645693',
    projectId: 'e-commerce-fa443',
    databaseURL: 'https://e-commerce-fa443-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'e-commerce-fa443.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdX3kON0j3wNmg4wgh75l_G6J6QrkfpIg',
    appId: '1:310222645693:ios:a0fa1d0e3859d296b94ad4',
    messagingSenderId: '310222645693',
    projectId: 'e-commerce-fa443',
    databaseURL: 'https://e-commerce-fa443-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'e-commerce-fa443.appspot.com',
    iosClientId: '310222645693-g0ujoj0l923nqmnped0devq4csm3ns74.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdX3kON0j3wNmg4wgh75l_G6J6QrkfpIg',
    appId: '1:310222645693:ios:a0fa1d0e3859d296b94ad4',
    messagingSenderId: '310222645693',
    projectId: 'e-commerce-fa443',
    databaseURL: 'https://e-commerce-fa443-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'e-commerce-fa443.appspot.com',
    iosClientId: '310222645693-g0ujoj0l923nqmnped0devq4csm3ns74.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );
}
